# Generated by Django 5.0 on 2024-02-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="scheduled_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 20, 11, 33, 6, 246518, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 20, 11, 33, 6, 246518, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
