# Generated by Django 5.0 on 2024-02-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0002_alter_appointment_scheduled_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="order_number",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="scheduled_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="clinic.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="clinic.patient",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionmedicine",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dosages",
                to="clinic.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
