# Generated by Django 5.0 on 2024-02-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0003_alter_appointment_order_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="scheduled_date",
            field=models.DateField(),
        ),
    ]
