# Generated by Django 5.0 on 2024-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinic", "0004_alter_appointment_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="exp_year",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="doctor",
            name="patients",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("General practice", "General practice"),
                    ("Clinical radiology", "Clinical radiology"),
                    ("Anaesthesia", "Anaesthesia"),
                    ("Ophthalmology", "Ophthalmology"),
                ],
                default="General practice",
                max_length=200,
            ),
        ),
    ]
